version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - PORT=80
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
