"""add rt and rw to balita

Revision ID: 43c09aa24658
Revises: 5052c1f93167
Create Date: 2025-07-22 08:34:19.566736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c09aa24658'
down_revision: Union[str, Sequence[str], None] = '5052c1f93167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balita', sa.Column('rt', sa.String(), nullable=True))
    op.add_column('balita', sa.Column('rw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balita', 'rw')
    op.drop_column('balita', 'rt')
    # ### end Alembic commands ###
