"""add z-score columns to pemeriksaan

Revision ID: a7de9c7e5149
Revises: ad911db3778d
Create Date: 2025-07-24 11:16:58.248865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7de9c7e5149'
down_revision: Union[str, Sequence[str], None] = 'ad911db3778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balita', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('balita', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.add_column('pemeriksaan', sa.Column('zscore_tbu', sa.Float(), nullable=True))
    op.add_column('pemeriksaan', sa.Column('kategori_tbu', sa.String(), nullable=True))
    op.add_column('pemeriksaan', sa.Column('zscore_bbtb', sa.Float(), nullable=True))
    op.add_column('pemeriksaan', sa.Column('kategori_bbtb', sa.String(), nullable=True))
    op.add_column('pemeriksaan', sa.Column('rekomendasi', sa.String(), nullable=True))
    op.drop_constraint(op.f('pemeriksaan_balita_id_fkey'), 'pemeriksaan', type_='foreignkey')
    op.create_foreign_key(None, 'pemeriksaan', 'balita', ['balita_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pemeriksaan', type_='foreignkey')
    op.create_foreign_key(op.f('pemeriksaan_balita_id_fkey'), 'pemeriksaan', 'balita', ['balita_id'], ['id'])
    op.drop_column('pemeriksaan', 'rekomendasi')
    op.drop_column('pemeriksaan', 'kategori_bbtb')
    op.drop_column('pemeriksaan', 'zscore_bbtb')
    op.drop_column('pemeriksaan', 'kategori_tbu')
    op.drop_column('pemeriksaan', 'zscore_tbu')
    op.alter_column('balita', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('balita', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
